export const HOST_AUDIO_BASE_PATH = "/audio/host";

const HOST_AUDIO_FILE_NAMES: Record<string, string> = {
  "night-wolves": "天黑请闭眼-狼人请睁眼-请选择今晚的击杀目标",
  "night-wolf-beauty": "狼美人请睁眼-请选择今晚魅惑的玩家-也可以选择不魅惑",
  "night-guard": "守卫请睁眼-请选择一名玩家守护-也可以选择空守",
  "night-seer": "预言家请睁眼-请选择一名玩家查验身份",
  "night-witch": "女巫请睁眼-请确认昨夜刀口-选择是否使用药品",
  "dawn-report": "天亮了-公布昨夜情况",
  "dawn-peaceful": "昨夜平安夜",
  "dawn-deaths": "昨夜死亡的是",
  dead: "死亡",
  "day-speech-start": "开始白天发言",
  please: "请",
  speak: "发言",
  "please-speak": "请发言",
  "sheriff-nomination-start": "警长竞选开始-所有存活玩家选择是否上警",
  "sheriff-nomination-human": "轮到你选择是否上警",
  "sheriff-nomination-prompt": "请选择是否上警",
  "sheriff-nominated": "选择上警",
  "sheriff-nomination-none": "无人选择上警-本局没有产生警长",
  "sheriff-speech-start": "警上发言开始",
  "sheriff-speech-human": "轮到你发表警长竞选发言",
  "sheriff-speech-prompt": "请发表警长竞选发言",
  "sheriff-withdrawal-start": "进入退水阶段-警上候选人依次选择是否退水",
  "sheriff-withdrew": "选择退水",
  "sheriff-vote-start": "进入警长投票阶段-警下玩家开始投票",
  "sheriff-pk-speech-start": "警长投票平票-进入PK发言",
  "sheriff-pk-speech-human": "轮到你发表警长PK发言",
  "sheriff-pk-speech-prompt": "请发表警长PK发言",
  "sheriff-pk-vote-start": "进入警长PK复投",
  "sheriff-handoff-start": "警徽移交窗口开启",
  "sheriff-handoff-human": "轮到你选择移交警徽或撕掉警徽",
  "sheriff-handoff-prompt": "请选择移交警徽或撕掉警徽",
  vote: "投票",
  "day-vote-start": "进入投票阶段",
  "vote-revealed": "公布票数",
  "vote-tie": "平票-今日无人放逐",
  exiled: "被放逐出局",
  "idiot-revealed": "白痴翻牌免死-失去投票权",
  "hunter-taken": "被猎人带走",
  "wolf-king-taken": "被狼王带走",
  "white-wolf-king-exploded": "白狼王自爆",
  "white-wolf-king-taken": "被白狼王带走",
  "wolf-beauty-charmed": "狼美人出局-触发魅惑",
  "wolf-beauty-taken": "殉情出局",
  "last-words": "请发表遗言",
  "hunter-shot": "猎人进入开枪窗口",
  "hunter-shot-human": "猎人出局-轮到你选择是否开枪",
  "wolf-king-shot": "狼王进入开枪窗口",
  "wolf-king-shot-human": "狼王出局-轮到你选择是否开枪",
  "knight-duel": "骑士进入决斗窗口",
  "knight-duel-human": "轮到你选择是否发动骑士决斗",
  "knight-duel-success": "骑士决斗成功",
  "knight-duel-failed": "骑士决斗失败-骑士出局",
  "knight-duel-taken": "被骑士决斗带走",
  "your-turn-speak": "轮到你发言",
  "your-turn-vote": "轮到你投票",
  "game-over-good": "好人阵营获胜",
  "game-over-wolves": "狼人阵营获胜",
  "flow-next": "流程继续推进",
  ...Object.fromEntries(Array.from({ length: 12 }, (_, index) => [`seat-${index + 1}`, `${index + 1}号`])),
};

export function hostAudioFileName(name: string): string {
  return HOST_AUDIO_FILE_NAMES[name] ?? name;
}

export function hostAudioSrc(name: string, extension = "mp3"): string {
  return `${HOST_AUDIO_BASE_PATH}/${hostAudioFileName(name)}.${extension}`;
}
